version: '3'

services:

#  app:
#    build: .
#    container_name: my_cont
#    restart: always
#    env_file:
#      - .env
#    volumes:
#      - ./:/wd
#    ports:
#      - ${PORT}:${PORT}
#
#    depends_on:
#      - db

  db:
    image: postgres:14.4
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  postgres_data:
  redis-data:

networks:
  default:
    driver: bridge